"""002_remove_max_tenants_max_users

Revision ID: 7666a9c36796
Revises: c2b6c43bb09f
Create Date: 2026-02-22 09:14:37.857423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7666a9c36796'
down_revision: Union[str, Sequence[str], None] = 'c2b6c43bb09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'max_tenants')
    op.drop_column('organizations', 'max_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('max_users', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('max_tenants', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
