"""Remove is_pinned from conversations table

Revision ID: 01743198757f
Revises: f00f7482b184
Create Date: 2026-01-05 11:55:43.642646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01743198757f'
down_revision: Union[str, Sequence[str], None] = 'f00f7482b184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('application_id', sa.String(length=100), nullable=False))
    op.create_index('ix_conversations_application', 'conversations', ['application_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    # Note: is_pinned was never added to DB, pinning is done via conversation_user_favorites
    op.alter_column('custom_group_members', 'role',
               existing_type=postgresql.ENUM('READ', 'WRITE', 'ADMIN', name='permissionactionenum'),
               type_=sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.alter_column('custom_group_members', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_group_members', 'id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('custom_group_members', 'role',
               existing_type=sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True),
               type_=postgresql.ENUM('READ', 'WRITE', 'ADMIN', name='permissionactionenum'),
               existing_nullable=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index('ix_conversations_application', table_name='conversations')
    op.drop_column('conversations', 'application_id')
    # ### end Alembic commands ###
