"""refactor_resource_permissions_to_members

Revision ID: 0ee03c5be1e8
Revises: 4891e5353454
Create Date: 2025-12-19 20:44:10.965574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ee03c5be1e8'
down_revision: Union[str, Sequence[str], None] = '4891e5353454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('principal_type', sa.Enum('IDENTITY_USER', 'IDENTITY_GROUP', 'CUSTOM_GROUP', name='principal_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'principal_id', 'principal_type', name='uq_application_members')
    )
    op.create_index('ix_am_application', 'application_members', ['application_id'], unique=False)
    op.create_index('ix_am_principal', 'application_members', ['principal_id'], unique=False)
    op.create_table('autonomous_agent_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('autonomous_agent_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('principal_type', sa.Enum('IDENTITY_USER', 'IDENTITY_GROUP', 'CUSTOM_GROUP', name='principal_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['autonomous_agent_id'], ['autonomous_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('autonomous_agent_id', 'principal_id', 'principal_type', name='uq_autonomous_agent_members')
    )
    op.create_index('ix_aam_autonomous_agent', 'autonomous_agent_members', ['autonomous_agent_id'], unique=False)
    op.create_index('ix_aam_principal', 'autonomous_agent_members', ['principal_id'], unique=False)
    op.create_table('conversation_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('principal_type', sa.Enum('IDENTITY_USER', 'IDENTITY_GROUP', 'CUSTOM_GROUP', name='principal_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'principal_id', 'principal_type', name='uq_conversation_members')
    )
    op.create_index('ix_cm_conversation', 'conversation_members', ['conversation_id'], unique=False)
    op.create_index('ix_cm_principal', 'conversation_members', ['principal_id'], unique=False)
    op.create_table('credential_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('principal_type', sa.Enum('IDENTITY_USER', 'IDENTITY_GROUP', 'CUSTOM_GROUP', name='principal_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id', 'principal_id', 'principal_type', name='uq_credential_members')
    )
    op.create_index('ix_crm_credential', 'credential_members', ['credential_id'], unique=False)
    op.create_index('ix_crm_principal', 'credential_members', ['principal_id'], unique=False)
    op.create_table('application_member_permissions',
    sa.Column('application_member_id', sa.String(length=36), nullable=False),
    sa.Column('permission', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['application_member_id'], ['application_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_member_id', 'permission', name='uq_application_member_permissions')
    )
    op.create_index('ix_amp_member', 'application_member_permissions', ['application_member_id'], unique=False)
    op.create_table('autonomous_agent_member_permissions',
    sa.Column('autonomous_agent_member_id', sa.String(length=36), nullable=False),
    sa.Column('permission', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['autonomous_agent_member_id'], ['autonomous_agent_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('autonomous_agent_member_id', 'permission', name='uq_autonomous_agent_member_permissions')
    )
    op.create_index('ix_aamp_member', 'autonomous_agent_member_permissions', ['autonomous_agent_member_id'], unique=False)
    op.create_table('conversation_member_permissions',
    sa.Column('conversation_member_id', sa.String(length=36), nullable=False),
    sa.Column('permission', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['conversation_member_id'], ['conversation_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_member_id', 'permission', name='uq_conversation_member_permissions')
    )
    op.create_index('ix_cmp_member', 'conversation_member_permissions', ['conversation_member_id'], unique=False)
    op.create_table('credential_member_permissions',
    sa.Column('credential_member_id', sa.String(length=36), nullable=False),
    sa.Column('permission', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['credential_member_id'], ['credential_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_member_id', 'permission', name='uq_credential_member_permissions')
    )
    op.create_index('ix_crmp_member', 'credential_member_permissions', ['credential_member_id'], unique=False)
    op.drop_index(op.f('ix_ap_lookup'), table_name='application_permissions')
    op.drop_index(op.f('ix_ap_principal'), table_name='application_permissions')
    op.drop_table('application_permissions')
    op.drop_index(op.f('ix_cp_lookup'), table_name='conversation_permissions')
    op.drop_index(op.f('ix_cp_principal'), table_name='conversation_permissions')
    op.drop_table('conversation_permissions')
    op.drop_index(op.f('ix_crp_lookup'), table_name='credential_permissions')
    op.drop_index(op.f('ix_crp_principal'), table_name='credential_permissions')
    op.drop_table('credential_permissions')
    op.drop_index(op.f('ix_aap_lookup'), table_name='autonomous_agent_permissions')
    op.drop_index(op.f('ix_aap_principal'), table_name='autonomous_agent_permissions')
    op.drop_table('autonomous_agent_permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autonomous_agent_permissions',
    sa.Column('autonomous_agent_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.CheckConstraint("action::text = ANY (ARRAY['READ'::character varying, 'WRITE'::character varying, 'ADMIN'::character varying]::text[])", name=op.f('permission_action')),
    sa.ForeignKeyConstraint(['autonomous_agent_id'], ['autonomous_agents.id'], name=op.f('autonomous_agent_permissions_autonomous_agent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('autonomous_agent_permissions_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('autonomous_agent_permissions_pkey')),
    sa.UniqueConstraint('tenant_id', 'autonomous_agent_id', 'principal_id', 'action', name=op.f('uq_aap'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_aap_principal'), 'autonomous_agent_permissions', ['principal_id'], unique=False)
    op.create_index(op.f('ix_aap_lookup'), 'autonomous_agent_permissions', ['tenant_id', 'autonomous_agent_id'], unique=False)
    op.create_table('credential_permissions',
    sa.Column('credential_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.CheckConstraint("action::text = ANY (ARRAY['READ'::character varying, 'WRITE'::character varying, 'ADMIN'::character varying]::text[])", name=op.f('permission_action')),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], name=op.f('credential_permissions_credential_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('credential_permissions_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('credential_permissions_pkey')),
    sa.UniqueConstraint('tenant_id', 'credential_id', 'principal_id', 'action', name=op.f('uq_crp'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_crp_principal'), 'credential_permissions', ['principal_id'], unique=False)
    op.create_index(op.f('ix_crp_lookup'), 'credential_permissions', ['tenant_id', 'credential_id'], unique=False)
    op.create_table('conversation_permissions',
    sa.Column('conversation_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.CheckConstraint("action::text = ANY (ARRAY['READ'::character varying, 'WRITE'::character varying, 'ADMIN'::character varying]::text[])", name=op.f('permission_action')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('conversation_permissions_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('conversation_permissions_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_permissions_pkey')),
    sa.UniqueConstraint('tenant_id', 'conversation_id', 'principal_id', 'action', name=op.f('uq_cp'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_cp_principal'), 'conversation_permissions', ['principal_id'], unique=False)
    op.create_index(op.f('ix_cp_lookup'), 'conversation_permissions', ['tenant_id', 'conversation_id'], unique=False)
    op.create_table('application_permissions',
    sa.Column('application_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.CheckConstraint("action::text = ANY (ARRAY['READ'::character varying, 'WRITE'::character varying, 'ADMIN'::character varying]::text[])", name=op.f('permission_action')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('application_permissions_application_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('application_permissions_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('application_permissions_pkey')),
    sa.UniqueConstraint('tenant_id', 'application_id', 'principal_id', 'action', name=op.f('uq_ap'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_ap_principal'), 'application_permissions', ['principal_id'], unique=False)
    op.create_index(op.f('ix_ap_lookup'), 'application_permissions', ['tenant_id', 'application_id'], unique=False)
    op.drop_index('ix_crmp_member', table_name='credential_member_permissions')
    op.drop_table('credential_member_permissions')
    op.drop_index('ix_cmp_member', table_name='conversation_member_permissions')
    op.drop_table('conversation_member_permissions')
    op.drop_index('ix_aamp_member', table_name='autonomous_agent_member_permissions')
    op.drop_table('autonomous_agent_member_permissions')
    op.drop_index('ix_amp_member', table_name='application_member_permissions')
    op.drop_table('application_member_permissions')
    op.drop_index('ix_crm_principal', table_name='credential_members')
    op.drop_index('ix_crm_credential', table_name='credential_members')
    op.drop_table('credential_members')
    op.drop_index('ix_cm_principal', table_name='conversation_members')
    op.drop_index('ix_cm_conversation', table_name='conversation_members')
    op.drop_table('conversation_members')
    op.drop_index('ix_aam_principal', table_name='autonomous_agent_members')
    op.drop_index('ix_aam_autonomous_agent', table_name='autonomous_agent_members')
    op.drop_table('autonomous_agent_members')
    op.drop_index('ix_am_principal', table_name='application_members')
    op.drop_index('ix_am_application', table_name='application_members')
    op.drop_table('application_members')
    # ### end Alembic commands ###
