"""drop_supported_widgets_from_chat_agents

Revision ID: 10cd631f8cb4
Revises: a98a1760f645
Create Date: 2026-03-15 12:04:15.214796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10cd631f8cb4'
down_revision: Union[str, Sequence[str], None] = 'a98a1760f645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_agents', 'supported_widgets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_agents', sa.Column('supported_widgets', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
