"""drop notifications table

Revision ID: 15a44fdbf615
Revises: 34442da57d94
Create Date: 2026-02-10 22:29:30.491115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15a44fdbf615'
down_revision: Union[str, Sequence[str], None] = '34442da57d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_tenant_created'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_user_read'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=19), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=6), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=6), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.CheckConstraint("type::text = ANY (ARRAY['AGENT_RUN_FAILED'::character varying, 'CREDENTIAL_EXPIRING'::character varying, 'TRACE_IMPORTED'::character varying]::text[])", name=op.f('notification_type')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('notifications_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_tenant_user_read'), 'notifications', ['tenant_id', 'user_id', 'is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_created'), 'notifications', ['tenant_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
