"""Add principals table and remove custom_groups

Revision ID: 172b16f13007
Revises: 
Create Date: 2025-12-26 07:58:06.719672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '172b16f13007'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('type', sa.Enum('N8N', 'MICROSOFT_FOUNDRY', 'REST_API', name='application_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('config', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_applications_tenant', 'applications', ['tenant_id'], unique=False)
    op.create_table('autonomous_agents',
    sa.Column('config', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_autonomous_agents_tenant', 'autonomous_agents', ['tenant_id'], unique=False)
    op.create_table('chat_widgets',
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('config', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_widgets_tenant', 'chat_widgets', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_tenant', 'conversations', ['tenant_id'], unique=False)
    op.create_table('credentials',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('credential_uri', sa.String(length=2000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credentials_tenant', 'credentials', ['tenant_id'], unique=False)
    op.create_table('development_platforms',
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('iframe_url', sa.String(length=2000), nullable=False),
    sa.Column('config', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_development_platforms_tenant', 'development_platforms', ['tenant_id'], unique=False)
    op.create_table('principals',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('principal_type', sa.Enum('IDENTITY_USER', 'IDENTITY_GROUP', 'CUSTOM_GROUP', name='principal_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('principal_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'principal_id')
    )
    op.create_index('ix_principals_display_name', 'principals', ['display_name'], unique=False)
    op.create_index('ix_principals_mail', 'principals', ['mail'], unique=False)
    op.create_index('ix_principals_principal_type', 'principals', ['principal_type'], unique=False)
    op.create_index('ix_principals_tenant', 'principals', ['tenant_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tag_tenant_name')
    )
    op.create_index('ix_tags_name', 'tags', ['name'], unique=False)
    op.create_index('ix_tags_tenant', 'tags', ['tenant_id'], unique=False)
    op.create_table('application_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'principal_id'], ['principals.tenant_id', 'principals.principal_id'], name='fk_application_members_principal', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'principal_id', name='uq_application_members')
    )
    op.create_index('ix_am_application', 'application_members', ['application_id'], unique=False)
    op.create_index('ix_am_principal', 'application_members', ['principal_id'], unique=False)
    op.create_table('application_tags',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'tag_id', 'application_id')
    )
    op.create_index('ix_at_application', 'application_tags', ['application_id'], unique=False)
    op.create_index('ix_at_tag', 'application_tags', ['tag_id'], unique=False)
    op.create_table('application_user_favorites',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('application_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['principals.tenant_id', 'principals.principal_id'], name='fk_application_user_favorites_principal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id', 'application_id')
    )
    op.create_index('ix_auf_application', 'application_user_favorites', ['application_id'], unique=False)
    op.create_index('ix_auf_user', 'application_user_favorites', ['user_id'], unique=False)
    op.create_table('autonomous_agent_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('autonomous_agent_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['autonomous_agent_id'], ['autonomous_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'principal_id'], ['principals.tenant_id', 'principals.principal_id'], name='fk_autonomous_agent_members_principal', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('autonomous_agent_id', 'principal_id', name='uq_autonomous_agent_members')
    )
    op.create_index('ix_aam_autonomous_agent', 'autonomous_agent_members', ['autonomous_agent_id'], unique=False)
    op.create_index('ix_aam_principal', 'autonomous_agent_members', ['principal_id'], unique=False)
    op.create_table('autonomous_agent_tags',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('autonomous_agent_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['autonomous_agent_id'], ['autonomous_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'tag_id', 'autonomous_agent_id')
    )
    op.create_index('ix_aat_autonomous_agent', 'autonomous_agent_tags', ['autonomous_agent_id'], unique=False)
    op.create_index('ix_aat_tag', 'autonomous_agent_tags', ['tag_id'], unique=False)
    op.create_table('autonomous_agent_user_favorites',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('autonomous_agent_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['autonomous_agent_id'], ['autonomous_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['principals.tenant_id', 'principals.principal_id'], name='fk_autonomous_agent_user_favorites_principal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id', 'autonomous_agent_id')
    )
    op.create_index('ix_aauf_autonomous_agent', 'autonomous_agent_user_favorites', ['autonomous_agent_id'], unique=False)
    op.create_index('ix_aauf_user', 'autonomous_agent_user_favorites', ['user_id'], unique=False)
    op.create_table('chat_widget_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('chat_widget_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['chat_widget_id'], ['chat_widgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'principal_id'], ['principals.tenant_id', 'principals.principal_id'], name='fk_chat_widget_members_principal', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_widget_id', 'principal_id', name='uq_chat_widget_members')
    )
    op.create_index('ix_cwm_chat_widget', 'chat_widget_members', ['chat_widget_id'], unique=False)
    op.create_index('ix_cwm_principal', 'chat_widget_members', ['principal_id'], unique=False)
    op.create_table('chat_widget_tags',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('chat_widget_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['chat_widget_id'], ['chat_widgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'tag_id', 'chat_widget_id')
    )
    op.create_index('ix_cwt_chat_widget', 'chat_widget_tags', ['chat_widget_id'], unique=False)
    op.create_index('ix_cwt_tag', 'chat_widget_tags', ['tag_id'], unique=False)
    op.create_table('conversation_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'principal_id'], ['principals.tenant_id', 'principals.principal_id'], name='fk_conversation_members_principal', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'principal_id', name='uq_conversation_members')
    )
    op.create_index('ix_cm_conversation', 'conversation_members', ['conversation_id'], unique=False)
    op.create_index('ix_cm_principal', 'conversation_members', ['principal_id'], unique=False)
    op.create_table('conversation_user_favorites',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['principals.tenant_id', 'principals.principal_id'], name='fk_conversation_user_favorites_principal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id', 'conversation_id')
    )
    op.create_index('ix_cuf_conversation', 'conversation_user_favorites', ['conversation_id'], unique=False)
    op.create_index('ix_cuf_user', 'conversation_user_favorites', ['user_id'], unique=False)
    op.create_table('credential_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'principal_id'], ['principals.tenant_id', 'principals.principal_id'], name='fk_credential_members_principal', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id', 'principal_id', name='uq_credential_members')
    )
    op.create_index('ix_crm_credential', 'credential_members', ['credential_id'], unique=False)
    op.create_index('ix_crm_principal', 'credential_members', ['principal_id'], unique=False)
    op.create_table('credential_tags',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'tag_id', 'credential_id')
    )
    op.create_index('ix_crt_credential', 'credential_tags', ['credential_id'], unique=False)
    op.create_index('ix_crt_tag', 'credential_tags', ['tag_id'], unique=False)
    op.create_table('development_platform_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('development_platform_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['development_platform_id'], ['development_platforms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'principal_id'], ['principals.tenant_id', 'principals.principal_id'], name='fk_development_platform_members_principal', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('development_platform_id', 'principal_id', name='uq_development_platform_members')
    )
    op.create_index('ix_dpm_development_platform', 'development_platform_members', ['development_platform_id'], unique=False)
    op.create_index('ix_dpm_principal', 'development_platform_members', ['principal_id'], unique=False)
    op.create_table('development_platform_tags',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('development_platform_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['development_platform_id'], ['development_platforms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'tag_id', 'development_platform_id')
    )
    op.create_index('ix_dpt_development_platform', 'development_platform_tags', ['development_platform_id'], unique=False)
    op.create_index('ix_dpt_tag', 'development_platform_tags', ['tag_id'], unique=False)
    op.create_table('development_platform_user_favorites',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('development_platform_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['development_platform_id'], ['development_platforms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['principals.tenant_id', 'principals.principal_id'], name='fk_development_platform_user_favorites_principal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id', 'development_platform_id')
    )
    op.create_index('ix_dpuf_development_platform', 'development_platform_user_favorites', ['development_platform_id'], unique=False)
    op.create_index('ix_dpuf_user', 'development_platform_user_favorites', ['user_id'], unique=False)
    op.create_table('tenant_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'principal_id'], ['principals.tenant_id', 'principals.principal_id'], name='fk_tenant_members_principal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'principal_id', name='uq_tenant_members')
    )
    op.create_index('ix_tenant_members_principal', 'tenant_members', ['principal_id'], unique=False)
    op.create_index('ix_tenant_members_tenant', 'tenant_members', ['tenant_id'], unique=False)
    op.create_table('tenant_member_roles',
    sa.Column('tenant_member_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('READER', 'GLOBAL_ADMIN', 'CUSTOM_GROUPS_ADMIN', 'CUSTOM_GROUP_CREATOR', 'APPLICATIONS_ADMIN', 'APPLICATIONS_CREATOR', 'CREDENTIALS_ADMIN', 'CREDENTIALS_CREATOR', 'CONVERSATIONS_ADMIN', 'CONVERSATIONS_CREATOR', 'AUTONOMOUS_AGENTS_ADMIN', 'AUTONOMOUS_AGENTS_CREATOR', 'DEVELOPMENT_PLATFORMS_ADMIN', 'DEVELOPMENT_PLATFORMS_CREATOR', 'CHAT_WIDGETS_ADMIN', 'CHAT_WIDGETS_CREATOR', name='tenant_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tenant_member_id'], ['tenant_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_member_id', 'role', name='uq_tenant_member_roles')
    )
    op.create_index('ix_tmr_tenant_member', 'tenant_member_roles', ['tenant_member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tmr_tenant_member', table_name='tenant_member_roles')
    op.drop_table('tenant_member_roles')
    op.drop_index('ix_tenant_members_tenant', table_name='tenant_members')
    op.drop_index('ix_tenant_members_principal', table_name='tenant_members')
    op.drop_table('tenant_members')
    op.drop_index('ix_dpuf_user', table_name='development_platform_user_favorites')
    op.drop_index('ix_dpuf_development_platform', table_name='development_platform_user_favorites')
    op.drop_table('development_platform_user_favorites')
    op.drop_index('ix_dpt_tag', table_name='development_platform_tags')
    op.drop_index('ix_dpt_development_platform', table_name='development_platform_tags')
    op.drop_table('development_platform_tags')
    op.drop_index('ix_dpm_principal', table_name='development_platform_members')
    op.drop_index('ix_dpm_development_platform', table_name='development_platform_members')
    op.drop_table('development_platform_members')
    op.drop_index('ix_crt_tag', table_name='credential_tags')
    op.drop_index('ix_crt_credential', table_name='credential_tags')
    op.drop_table('credential_tags')
    op.drop_index('ix_crm_principal', table_name='credential_members')
    op.drop_index('ix_crm_credential', table_name='credential_members')
    op.drop_table('credential_members')
    op.drop_index('ix_cuf_user', table_name='conversation_user_favorites')
    op.drop_index('ix_cuf_conversation', table_name='conversation_user_favorites')
    op.drop_table('conversation_user_favorites')
    op.drop_index('ix_cm_principal', table_name='conversation_members')
    op.drop_index('ix_cm_conversation', table_name='conversation_members')
    op.drop_table('conversation_members')
    op.drop_index('ix_cwt_tag', table_name='chat_widget_tags')
    op.drop_index('ix_cwt_chat_widget', table_name='chat_widget_tags')
    op.drop_table('chat_widget_tags')
    op.drop_index('ix_cwm_principal', table_name='chat_widget_members')
    op.drop_index('ix_cwm_chat_widget', table_name='chat_widget_members')
    op.drop_table('chat_widget_members')
    op.drop_index('ix_aauf_user', table_name='autonomous_agent_user_favorites')
    op.drop_index('ix_aauf_autonomous_agent', table_name='autonomous_agent_user_favorites')
    op.drop_table('autonomous_agent_user_favorites')
    op.drop_index('ix_aat_tag', table_name='autonomous_agent_tags')
    op.drop_index('ix_aat_autonomous_agent', table_name='autonomous_agent_tags')
    op.drop_table('autonomous_agent_tags')
    op.drop_index('ix_aam_principal', table_name='autonomous_agent_members')
    op.drop_index('ix_aam_autonomous_agent', table_name='autonomous_agent_members')
    op.drop_table('autonomous_agent_members')
    op.drop_index('ix_auf_user', table_name='application_user_favorites')
    op.drop_index('ix_auf_application', table_name='application_user_favorites')
    op.drop_table('application_user_favorites')
    op.drop_index('ix_at_tag', table_name='application_tags')
    op.drop_index('ix_at_application', table_name='application_tags')
    op.drop_table('application_tags')
    op.drop_index('ix_am_principal', table_name='application_members')
    op.drop_index('ix_am_application', table_name='application_members')
    op.drop_table('application_members')
    op.drop_index('ix_tags_tenant', table_name='tags')
    op.drop_index('ix_tags_name', table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_principals_tenant', table_name='principals')
    op.drop_index('ix_principals_principal_type', table_name='principals')
    op.drop_index('ix_principals_mail', table_name='principals')
    op.drop_index('ix_principals_display_name', table_name='principals')
    op.drop_table('principals')
    op.drop_index('ix_development_platforms_tenant', table_name='development_platforms')
    op.drop_table('development_platforms')
    op.drop_index('ix_credentials_tenant', table_name='credentials')
    op.drop_table('credentials')
    op.drop_index('ix_conversations_tenant', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_chat_widgets_tenant', table_name='chat_widgets')
    op.drop_table('chat_widgets')
    op.drop_index('ix_autonomous_agents_tenant', table_name='autonomous_agents')
    op.drop_table('autonomous_agents')
    op.drop_index('ix_applications_tenant', table_name='applications')
    op.drop_table('applications')
    op.drop_table('tenants')
    # ### end Alembic commands ###
