"""add chat widget and re-act agent user favorites

Revision ID: 34442da57d94
Revises: a43927c95366
Create Date: 2026-02-10 08:13:30.872247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from unifiedui.core.database.models import HighPrecisionDateTime


# revision identifiers, used by Alembic.
revision: str = '34442da57d94'
down_revision: Union[str, Sequence[str], None] = 'a43927c95366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_widget_user_favorites',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('chat_widget_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['chat_widget_id'], ['chat_widgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['principals.tenant_id', 'principals.principal_id'], name='fk_chat_widget_user_favorites_principal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id', 'chat_widget_id')
    )
    op.create_index('ix_cwuf_chat_widget', 'chat_widget_user_favorites', ['chat_widget_id'], unique=False)
    op.create_index('ix_cwuf_user', 'chat_widget_user_favorites', ['user_id'], unique=False)
    op.create_table('re_act_agent_user_favorites',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('re_act_agent_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['re_act_agent_id'], ['re_act_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['principals.tenant_id', 'principals.principal_id'], name='fk_re_act_agent_user_favorites_principal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id', 're_act_agent_id')
    )
    op.create_index('ix_rauf_re_act_agent', 're_act_agent_user_favorites', ['re_act_agent_id'], unique=False)
    op.create_index('ix_rauf_user', 're_act_agent_user_favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rauf_user', table_name='re_act_agent_user_favorites')
    op.drop_index('ix_rauf_re_act_agent', table_name='re_act_agent_user_favorites')
    op.drop_table('re_act_agent_user_favorites')
    op.drop_index('ix_cwuf_user', table_name='chat_widget_user_favorites')
    op.drop_index('ix_cwuf_chat_widget', table_name='chat_widget_user_favorites')
    op.drop_table('chat_widget_user_favorites')
    # ### end Alembic commands ###
