"""add_custom_group_creator_permission

Revision ID: 431e4acb7f58
Revises: 93cdd1858cc1
Create Date: 2025-12-17 14:20:44.761453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431e4acb7f58'
down_revision: Union[str, Sequence[str], None] = '93cdd1858cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
