"""add_credential_vault_columns

Revision ID: 4891e5353454
Revises: 4f1fd1c7855f
Create Date: 2025-12-19 20:06:44.340636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4891e5353454'
down_revision: Union[str, Sequence[str], None] = '4f1fd1c7855f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('credentials', sa.Column('source', sa.String(length=255), nullable=False))
    op.add_column('credentials', sa.Column('credential_uri', sa.String(length=2000), nullable=False))
    op.drop_column('credentials', 'config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('credentials', 'credential_uri')
    op.drop_column('credentials', 'source')
    op.drop_column('credentials', 'type')
    # ### end Alembic commands ###
