"""add_audit_fields

Revision ID: 4f15ab679769
Revises: 8dec5d126360
Create Date: 2025-12-17 10:38:41.974405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f15ab679769'
down_revision: Union[str, Sequence[str], None] = '8dec5d126360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_permissions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('application_permissions', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('application_permissions', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('applications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('applications', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('applications', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('autonomous_agent_permissions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('autonomous_agent_permissions', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('autonomous_agent_permissions', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('autonomous_agents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('autonomous_agents', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('autonomous_agents', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('conversation_permissions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('conversation_permissions', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('conversation_permissions', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('conversations', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('conversations', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('credential_permissions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('credential_permissions', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('credential_permissions', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('credentials', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('credentials', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('credentials', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('custom_group_permissions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('custom_group_permissions', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('custom_group_permissions', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('custom_groups', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('custom_groups', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('custom_groups', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('tenant_roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tenant_roles', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('tenant_roles', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tenants', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('updated_by', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'updated_by')
    op.drop_column('tenants', 'created_by')
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenant_roles', 'updated_by')
    op.drop_column('tenant_roles', 'created_by')
    op.drop_column('tenant_roles', 'updated_at')
    op.drop_column('custom_groups', 'updated_by')
    op.drop_column('custom_groups', 'created_by')
    op.drop_column('custom_groups', 'updated_at')
    op.drop_column('custom_group_permissions', 'updated_by')
    op.drop_column('custom_group_permissions', 'created_by')
    op.drop_column('custom_group_permissions', 'updated_at')
    op.drop_column('credentials', 'updated_by')
    op.drop_column('credentials', 'created_by')
    op.drop_column('credentials', 'updated_at')
    op.drop_column('credential_permissions', 'updated_by')
    op.drop_column('credential_permissions', 'created_by')
    op.drop_column('credential_permissions', 'updated_at')
    op.drop_column('conversations', 'updated_by')
    op.drop_column('conversations', 'created_by')
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversation_permissions', 'updated_by')
    op.drop_column('conversation_permissions', 'created_by')
    op.drop_column('conversation_permissions', 'updated_at')
    op.drop_column('autonomous_agents', 'updated_by')
    op.drop_column('autonomous_agents', 'created_by')
    op.drop_column('autonomous_agents', 'updated_at')
    op.drop_column('autonomous_agent_permissions', 'updated_by')
    op.drop_column('autonomous_agent_permissions', 'created_by')
    op.drop_column('autonomous_agent_permissions', 'updated_at')
    op.drop_column('applications', 'updated_by')
    op.drop_column('applications', 'created_by')
    op.drop_column('applications', 'updated_at')
    op.drop_column('application_permissions', 'updated_by')
    op.drop_column('application_permissions', 'created_by')
    op.drop_column('application_permissions', 'updated_at')
    # ### end Alembic commands ###
