"""refactor_custom_groups_to_three_tables

Revision ID: 4f1fd1c7855f
Revises: 431e4acb7f58
Create Date: 2025-12-17 14:47:36.712359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f1fd1c7855f'
down_revision: Union[str, Sequence[str], None] = '431e4acb7f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_group_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('custom_group_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('principal_type', sa.Enum('IDENTITY_USER', 'IDENTITY_GROUP', 'CUSTOM_GROUP', name='principal_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['custom_group_id'], ['custom_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_group_id', 'principal_id', 'principal_type', name='uq_custom_group_members')
    )
    op.create_index('ix_cgm_custom_group', 'custom_group_members', ['custom_group_id'], unique=False)
    op.create_index('ix_cgm_principal', 'custom_group_members', ['principal_id'], unique=False)
    op.create_table('custom_group_member_permissions',
    sa.Column('custom_group_member_id', sa.String(length=36), nullable=False),
    sa.Column('permission', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['custom_group_member_id'], ['custom_group_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_group_member_id', 'permission', name='uq_custom_group_member_permissions')
    )
    op.create_index('ix_cgmp_member', 'custom_group_member_permissions', ['custom_group_member_id'], unique=False)
    op.drop_index(op.f('ix_cgp_lookup'), table_name='custom_group_permissions')
    op.drop_index(op.f('ix_cgp_principal'), table_name='custom_group_permissions')
    op.drop_table('custom_group_permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_group_permissions',
    sa.Column('custom_group_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.CheckConstraint("action::text = ANY (ARRAY['READ'::character varying, 'WRITE'::character varying, 'ADMIN'::character varying]::text[])", name=op.f('permission_action')),
    sa.ForeignKeyConstraint(['custom_group_id'], ['custom_groups.id'], name=op.f('custom_group_permissions_custom_group_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('custom_group_permissions_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('custom_group_permissions_pkey')),
    sa.UniqueConstraint('tenant_id', 'custom_group_id', 'principal_id', 'action', name=op.f('uq_cgp'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_cgp_principal'), 'custom_group_permissions', ['principal_id'], unique=False)
    op.create_index(op.f('ix_cgp_lookup'), 'custom_group_permissions', ['tenant_id', 'custom_group_id'], unique=False)
    op.drop_index('ix_cgmp_member', table_name='custom_group_member_permissions')
    op.drop_table('custom_group_member_permissions')
    op.drop_index('ix_cgm_principal', table_name='custom_group_members')
    op.drop_index('ix_cgm_custom_group', table_name='custom_group_members')
    op.drop_table('custom_group_members')
    # ### end Alembic commands ###
