"""change_permission_to_string

Revision ID: 69010a7b316f
Revises: a991b16bd047
Create Date: 2025-12-17 11:58:17.908481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69010a7b316f'
down_revision: Union[str, Sequence[str], None] = 'a991b16bd047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_member_permissions', 'permission',
               existing_type=sa.VARCHAR(length=23),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_member_permissions', 'permission',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=23),
               existing_nullable=False)
    # ### end Alembic commands ###
