"""resize uuid columns from varchar100 to varchar36

Revision ID: 7a68f0fc2759
Revises: 2dcb01103929
Create Date: 2026-02-08 00:41:36.612289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a68f0fc2759'
down_revision: Union[str, Sequence[str], None] = '2dcb01103929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_members', 'id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('application_tags', 'application_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('application_user_favorites', 'application_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('applications', 'id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('autonomous_agent_members', 'id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('autonomous_agent_tags', 'autonomous_agent_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('autonomous_agent_user_favorites', 'autonomous_agent_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('autonomous_agents', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('N8N', name='autonomous_agent_type', native_enum=False, create_constraint=True),
               existing_nullable=False,
               existing_server_default=sa.text("'N8N'::character varying"))
    op.alter_column('autonomous_agents', 'primary_key_vault_uri',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('autonomous_agents', 'secondary_key_vault_uri',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('autonomous_agents', 'id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('chat_widget_members', 'id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('chat_widget_tags', 'chat_widget_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('chat_widgets', 'id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('conversation_members', 'id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('conversation_user_favorites', 'conversation_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('conversations', 'application_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('credential_members', 'id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('credential_tags', 'credential_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('credentials', 'id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('custom_group_members', 'id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('tenant_members', 'role',
               existing_type=sa.VARCHAR(length=29),
               type_=sa.Enum('READER', 'GLOBAL_ADMIN', 'CUSTOM_GROUPS_ADMIN', 'CUSTOM_GROUP_CREATOR', 'APPLICATIONS_ADMIN', 'APPLICATIONS_CREATOR', 'CREDENTIALS_ADMIN', 'CREDENTIALS_CREATOR', 'CONVERSATIONS_ADMIN', 'CONVERSATIONS_CREATOR', 'AUTONOMOUS_AGENTS_ADMIN', 'AUTONOMOUS_AGENTS_CREATOR', 'CHAT_WIDGETS_ADMIN', 'CHAT_WIDGETS_CREATOR', 'REACT_AGENT_ADMIN', 'REACT_AGENT_CREATOR', name='tenant_role', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.alter_column('tenant_members', 'id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('tenants', 'id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('tool_members', 'tool_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('tool_members', 'id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('tool_tags', 'tool_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_tool_tags_tag'), table_name='tool_tags')
    op.drop_index(op.f('ix_tool_tags_tool'), table_name='tool_tags')
    op.create_index('ix_tt_tag', 'tool_tags', ['tag_id'], unique=False)
    op.create_index('ix_tt_tool', 'tool_tags', ['tool_id'], unique=False)
    op.alter_column('tools', 'credential_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('tools', 'id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_tools_credential'), table_name='tools')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tools_credential'), 'tools', ['credential_id'], unique=False)
    op.alter_column('tools', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('tools', 'credential_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index('ix_tt_tool', table_name='tool_tags')
    op.drop_index('ix_tt_tag', table_name='tool_tags')
    op.create_index(op.f('ix_tool_tags_tool'), 'tool_tags', ['tool_id'], unique=False)
    op.create_index(op.f('ix_tool_tags_tag'), 'tool_tags', ['tag_id'], unique=False)
    op.alter_column('tool_tags', 'tool_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('tool_members', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('tool_members', 'tool_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('tenants', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('tenant_members', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('tenant_members', 'role',
               existing_type=sa.Enum('READER', 'GLOBAL_ADMIN', 'CUSTOM_GROUPS_ADMIN', 'CUSTOM_GROUP_CREATOR', 'APPLICATIONS_ADMIN', 'APPLICATIONS_CREATOR', 'CREDENTIALS_ADMIN', 'CREDENTIALS_CREATOR', 'CONVERSATIONS_ADMIN', 'CONVERSATIONS_CREATOR', 'AUTONOMOUS_AGENTS_ADMIN', 'AUTONOMOUS_AGENTS_CREATOR', 'CHAT_WIDGETS_ADMIN', 'CHAT_WIDGETS_CREATOR', 'REACT_AGENT_ADMIN', 'REACT_AGENT_CREATOR', name='tenant_role', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=29),
               existing_nullable=False)
    op.alter_column('custom_group_members', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('credentials', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('credential_tags', 'credential_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('credential_members', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('conversations', 'application_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('conversation_user_favorites', 'conversation_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('conversation_members', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('chat_widgets', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('chat_widget_tags', 'chat_widget_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('chat_widget_members', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('autonomous_agents', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('autonomous_agents', 'secondary_key_vault_uri',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('autonomous_agents', 'primary_key_vault_uri',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('autonomous_agents', 'type',
               existing_type=sa.Enum('N8N', name='autonomous_agent_type', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'N8N'::character varying"))
    op.alter_column('autonomous_agent_user_favorites', 'autonomous_agent_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('autonomous_agent_tags', 'autonomous_agent_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('autonomous_agent_members', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('applications', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('application_user_favorites', 'application_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('application_tags', 'application_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('application_members', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
