"""initial_schema

Revision ID: 8dec5d126360
Revises: 
Create Date: 2025-12-17 10:22:14.891321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dec5d126360'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('config', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_applications_tenant', 'applications', ['tenant_id'], unique=False)
    op.create_table('autonomous_agents',
    sa.Column('config', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_autonomous_agents_tenant', 'autonomous_agents', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_tenant', 'conversations', ['tenant_id'], unique=False)
    op.create_table('credentials',
    sa.Column('config', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credentials_tenant', 'credentials', ['tenant_id'], unique=False)
    op.create_table('custom_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_custom_groups_tenant', 'custom_groups', ['tenant_id'], unique=False)
    op.create_table('tenant_roles',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('READER', 'GLOBAL_ADMIN', 'CUSTOM_GROUPS_ADMIN', 'APPLICATIONS_ADMIN', 'CREDENTIALS_ADMIN', 'AUTONOMOUS_AGENTS_ADMIN', name='tenant_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'principal_id', 'role', name='uq_tenant_roles')
    )
    op.create_index('ix_tenant_roles_principal', 'tenant_roles', ['principal_id'], unique=False)
    op.create_index('ix_tenant_roles_tenant', 'tenant_roles', ['tenant_id'], unique=False)
    op.create_table('application_permissions',
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'application_id', 'principal_id', 'action', name='uq_ap')
    )
    op.create_index('ix_ap_lookup', 'application_permissions', ['tenant_id', 'application_id'], unique=False)
    op.create_index('ix_ap_principal', 'application_permissions', ['principal_id'], unique=False)
    op.create_table('autonomous_agent_permissions',
    sa.Column('autonomous_agent_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['autonomous_agent_id'], ['autonomous_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'autonomous_agent_id', 'principal_id', 'action', name='uq_aap')
    )
    op.create_index('ix_aap_lookup', 'autonomous_agent_permissions', ['tenant_id', 'autonomous_agent_id'], unique=False)
    op.create_index('ix_aap_principal', 'autonomous_agent_permissions', ['principal_id'], unique=False)
    op.create_table('conversation_permissions',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'conversation_id', 'principal_id', 'action', name='uq_cp')
    )
    op.create_index('ix_cp_lookup', 'conversation_permissions', ['tenant_id', 'conversation_id'], unique=False)
    op.create_index('ix_cp_principal', 'conversation_permissions', ['principal_id'], unique=False)
    op.create_table('credential_permissions',
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'credential_id', 'principal_id', 'action', name='uq_crp')
    )
    op.create_index('ix_crp_lookup', 'credential_permissions', ['tenant_id', 'credential_id'], unique=False)
    op.create_index('ix_crp_principal', 'credential_permissions', ['principal_id'], unique=False)
    op.create_table('custom_group_permissions',
    sa.Column('custom_group_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['custom_group_id'], ['custom_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'custom_group_id', 'principal_id', 'action', name='uq_cgp')
    )
    op.create_index('ix_cgp_lookup', 'custom_group_permissions', ['tenant_id', 'custom_group_id'], unique=False)
    op.create_index('ix_cgp_principal', 'custom_group_permissions', ['principal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cgp_principal', table_name='custom_group_permissions')
    op.drop_index('ix_cgp_lookup', table_name='custom_group_permissions')
    op.drop_table('custom_group_permissions')
    op.drop_index('ix_crp_principal', table_name='credential_permissions')
    op.drop_index('ix_crp_lookup', table_name='credential_permissions')
    op.drop_table('credential_permissions')
    op.drop_index('ix_cp_principal', table_name='conversation_permissions')
    op.drop_index('ix_cp_lookup', table_name='conversation_permissions')
    op.drop_table('conversation_permissions')
    op.drop_index('ix_aap_principal', table_name='autonomous_agent_permissions')
    op.drop_index('ix_aap_lookup', table_name='autonomous_agent_permissions')
    op.drop_table('autonomous_agent_permissions')
    op.drop_index('ix_ap_principal', table_name='application_permissions')
    op.drop_index('ix_ap_lookup', table_name='application_permissions')
    op.drop_table('application_permissions')
    op.drop_index('ix_tenant_roles_tenant', table_name='tenant_roles')
    op.drop_index('ix_tenant_roles_principal', table_name='tenant_roles')
    op.drop_table('tenant_roles')
    op.drop_index('ix_custom_groups_tenant', table_name='custom_groups')
    op.drop_table('custom_groups')
    op.drop_index('ix_credentials_tenant', table_name='credentials')
    op.drop_table('credentials')
    op.drop_index('ix_conversations_tenant', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_autonomous_agents_tenant', table_name='autonomous_agents')
    op.drop_table('autonomous_agents')
    op.drop_index('ix_applications_tenant', table_name='applications')
    op.drop_table('applications')
    op.drop_table('tenants')
    # ### end Alembic commands ###
