"""auto migration

Revision ID: a43927c95366
Revises: 932c0fb2457a
Create Date: 2026-02-09 18:16:42.980207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
from sqlalchemy.dialects import postgresql

from unifiedui.core.database.models import HighPrecisionDateTime

# revision identifiers, used by Alembic.
revision: str = 'a43927c95366'
down_revision: Union[str, Sequence[str], None] = '932c0fb2457a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('AGENT_RUN_FAILED', 'CREDENTIAL_EXPIRING', 'TRACE_IMPORTED', name='notification_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_tenant_created', 'notifications', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_tenant_user_read', 'notifications', ['tenant_id', 'user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('re_act_agents',
    sa.Column('ai_model_ids', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('system_prompt', sa.String(length=8000), nullable=True),
    sa.Column('tool_ids', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('security_prompt', sa.String(length=8000), nullable=True),
    sa.Column('tool_use_prompt', sa.String(length=8000), nullable=True),
    sa.Column('response_prompt', sa.String(length=8000), nullable=True),
    sa.Column('greeting_messages', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_re_act_agents_tenant', 're_act_agents', ['tenant_id'], unique=False)
    op.create_table('recent_visits',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('visited_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'resource_type', 'resource_id', name='uq_recent_visits')
    )
    op.create_index('ix_recent_visits_user_time', 'recent_visits', ['tenant_id', 'user_id', 'visited_at'], unique=False)
    op.create_table('re_act_agent_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('re_act_agent_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['re_act_agent_id'], ['re_act_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'principal_id'], ['principals.tenant_id', 'principals.principal_id'], name='fk_re_act_agent_members_principal', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('re_act_agent_id', 'principal_id', name='uq_re_act_agent_members')
    )
    op.create_index('ix_re_act_agent_members_agent', 're_act_agent_members', ['re_act_agent_id'], unique=False)
    op.create_index('ix_re_act_agent_members_principal', 're_act_agent_members', ['principal_id'], unique=False)
    op.create_table('re_act_agent_tags',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('re_act_agent_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['re_act_agent_id'], ['re_act_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'tag_id', 're_act_agent_id')
    )
    op.create_index('ix_rat_agent', 're_act_agent_tags', ['re_act_agent_id'], unique=False)
    op.create_index('ix_rat_tag', 're_act_agent_tags', ['tag_id'], unique=False)
    op.execute("ALTER TABLE autonomous_agents DROP CONSTRAINT IF EXISTS autonomous_agent_type")
    op.alter_column('autonomous_agents', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('N8N', name='autonomous_agent_type', native_enum=False, create_constraint=True),
               existing_nullable=False,
               existing_server_default=sa.text("'N8N'::character varying"))
    op.alter_column('autonomous_agents', 'primary_key_vault_uri',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('autonomous_agents', 'secondary_key_vault_uri',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.execute("ALTER TABLE tenant_members DROP CONSTRAINT IF EXISTS tenant_role")
    op.alter_column('tenant_members', 'role',
               existing_type=sa.VARCHAR(length=29),
               type_=sa.Enum('READER', 'GLOBAL_ADMIN', 'CUSTOM_GROUPS_ADMIN', 'CUSTOM_GROUP_CREATOR', 'APPLICATIONS_ADMIN', 'APPLICATIONS_CREATOR', 'CREDENTIALS_ADMIN', 'CREDENTIALS_CREATOR', 'CONVERSATIONS_ADMIN', 'CONVERSATIONS_CREATOR', 'AUTONOMOUS_AGENTS_ADMIN', 'AUTONOMOUS_AGENTS_CREATOR', 'CHAT_WIDGETS_ADMIN', 'CHAT_WIDGETS_CREATOR', 'REACT_AGENT_ADMIN', 'REACT_AGENT_CREATOR', 'TENANT_AI_MODELS_ADMIN', name='tenant_role', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_tool_tags_tag'), table_name='tool_tags')
    op.drop_index(op.f('ix_tool_tags_tool'), table_name='tool_tags')
    op.create_index('ix_tt_tag', 'tool_tags', ['tag_id'], unique=False)
    op.create_index('ix_tt_tool', 'tool_tags', ['tool_id'], unique=False)
    op.drop_index(op.f('ix_tools_credential'), table_name='tools')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tools_credential'), 'tools', ['credential_id'], unique=False)
    op.drop_index('ix_tt_tool', table_name='tool_tags')
    op.drop_index('ix_tt_tag', table_name='tool_tags')
    op.create_index(op.f('ix_tool_tags_tool'), 'tool_tags', ['tool_id'], unique=False)
    op.create_index(op.f('ix_tool_tags_tag'), 'tool_tags', ['tag_id'], unique=False)
    op.alter_column('tenant_members', 'role',
               existing_type=sa.Enum('READER', 'GLOBAL_ADMIN', 'CUSTOM_GROUPS_ADMIN', 'CUSTOM_GROUP_CREATOR', 'APPLICATIONS_ADMIN', 'APPLICATIONS_CREATOR', 'CREDENTIALS_ADMIN', 'CREDENTIALS_CREATOR', 'CONVERSATIONS_ADMIN', 'CONVERSATIONS_CREATOR', 'AUTONOMOUS_AGENTS_ADMIN', 'AUTONOMOUS_AGENTS_CREATOR', 'CHAT_WIDGETS_ADMIN', 'CHAT_WIDGETS_CREATOR', 'REACT_AGENT_ADMIN', 'REACT_AGENT_CREATOR', 'TENANT_AI_MODELS_ADMIN', name='tenant_role', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=29),
               existing_nullable=False)
    op.alter_column('autonomous_agents', 'secondary_key_vault_uri',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('autonomous_agents', 'primary_key_vault_uri',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('autonomous_agents', 'type',
               existing_type=sa.Enum('N8N', name='autonomous_agent_type', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'N8N'::character varying"))
    op.drop_index('ix_rat_tag', table_name='re_act_agent_tags')
    op.drop_index('ix_rat_agent', table_name='re_act_agent_tags')
    op.drop_table('re_act_agent_tags')
    op.drop_index('ix_re_act_agent_members_principal', table_name='re_act_agent_members')
    op.drop_index('ix_re_act_agent_members_agent', table_name='re_act_agent_members')
    op.drop_table('re_act_agent_members')
    op.drop_index('ix_recent_visits_user_time', table_name='recent_visits')
    op.drop_table('recent_visits')
    op.drop_index('ix_re_act_agents_tenant', table_name='re_act_agents')
    op.drop_table('re_act_agents')
    op.drop_index('ix_notifications_tenant_user_read', table_name='notifications')
    op.drop_index('ix_notifications_tenant_created', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
