"""initial_schema

Revision ID: a75f474e1ca6
Revises:
Create Date: 2026-03-21 08:36:24.991212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
from sqlalchemy.dialects import postgresql
from unifiedui.core.database.models import HighPrecisionDateTime

# revision identifiers, used by Alembic.
revision: str = 'a75f474e1ca6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('identity_provider', sa.String(length=50), nullable=False),
    sa.Column('identity_tenant_id', sa.String(length=255), nullable=False),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_provider', 'identity_tenant_id', name='uq_org_idp'),
    sa.UniqueConstraint('name', name='uq_organization_name'),
    sa.UniqueConstraint('slug'),
    schema='unifiedui'
    )
    op.create_index('ix_org_idp', 'organizations', ['identity_provider', 'identity_tenant_id'], unique=False, schema='unifiedui')
    op.create_index('ix_org_slug', 'organizations', ['slug'], unique=False, schema='unifiedui')
    op.create_table('organization_members',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('principal_type', sa.Enum('IDENTITY_USER', 'IDENTITY_GROUP', 'CUSTOM_GROUP', name='principal_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('role', sa.Enum('ORGANISATION_GLOBAL_ADMIN', 'ORGANISATION_TENANT_ADMIN', 'ORGANISATION_TENANT_CREATOR', name='organization_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['unifiedui.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'principal_id', 'role', name='uq_org_member'),
    schema='unifiedui'
    )
    op.create_index('ix_org_member_org', 'organization_members', ['organization_id'], unique=False, schema='unifiedui')
    op.create_index('ix_org_member_principal', 'organization_members', ['principal_id'], unique=False, schema='unifiedui')
    op.create_table('tenants',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('environment_type', sa.Enum('SANDBOX', 'PRODUCTION', name='environment_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('previous_stage_id', sa.String(length=36), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('can_be_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['unifiedui.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_stage_id'], ['unifiedui.tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', 'environment_type', name='uq_tenant_org_name_env'),
    schema='unifiedui'
    )
    op.create_index('ix_tenant_org', 'tenants', ['organization_id'], unique=False, schema='unifiedui')
    op.create_table('autonomous_agents',
    sa.Column('type', sa.Enum('N8N', name='autonomous_agent_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('config', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allow_api_keys', sa.Boolean(), nullable=False),
    sa.Column('primary_key_vault_uri', sa.String(length=2000), nullable=True),
    sa.Column('secondary_key_vault_uri', sa.String(length=2000), nullable=True),
    sa.Column('last_full_import', HighPrecisionDateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_autonomous_agent_tenant_name'),
    schema='unifiedui'
    )
    op.create_index('ix_autonomous_agents_tenant', 'autonomous_agents', ['tenant_id'], unique=False, schema='unifiedui')
    op.create_table('chat_agents',
    sa.Column('type', sa.Enum('N8N', 'MICROSOFT_FOUNDRY', 'REST_API', 'REACT_AGENT', name='chat_agent_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('config', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('embed_allowed_origins', sa.String(length=2000), nullable=True),
    sa.Column('greeting_messages', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_chat_agent_tenant_name'),
    schema='unifiedui'
    )
    op.create_index('ix_chat_agents_tenant', 'chat_agents', ['tenant_id'], unique=False, schema='unifiedui')
    op.create_table('chat_widgets',
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('config', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_chat_widget_tenant_name'),
    schema='unifiedui'
    )
    op.create_index('ix_chat_widgets_tenant', 'chat_widgets', ['tenant_id'], unique=False, schema='unifiedui')
    op.create_table('credentials',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('credential_uri', sa.String(length=2000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_credential_tenant_name'),
    schema='unifiedui'
    )
    op.create_index('ix_credentials_tenant', 'credentials', ['tenant_id'], unique=False, schema='unifiedui')
    op.create_table('external_apps',
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('image_url', sa.String(length=2000), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_external_app_tenant_name'),
    schema='unifiedui'
    )
    op.create_index('ix_external_apps_tenant', 'external_apps', ['tenant_id'], unique=False, schema='unifiedui')
    op.create_table('principals',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('principal_type', sa.Enum('IDENTITY_USER', 'IDENTITY_GROUP', 'CUSTOM_GROUP', name='principal_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('principal_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'principal_id'),
    schema='unifiedui'
    )
    op.create_index('ix_principals_display_name', 'principals', ['display_name'], unique=False, schema='unifiedui')
    op.create_index('ix_principals_mail', 'principals', ['mail'], unique=False, schema='unifiedui')
    op.create_index('ix_principals_principal_type', 'principals', ['principal_type'], unique=False, schema='unifiedui')
    op.create_index('ix_principals_tenant', 'principals', ['tenant_id'], unique=False, schema='unifiedui')
    op.create_table('recent_visits',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('visited_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'resource_type', 'resource_id', name='uq_recent_visits'),
    schema='unifiedui'
    )
    op.create_index('ix_recent_visits_user_time', 'recent_visits', ['tenant_id', 'user_id', 'visited_at'], unique=False, schema='unifiedui')
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tag_tenant_name'),
    schema='unifiedui'
    )
    op.create_index('ix_tags_name', 'tags', ['name'], unique=False, schema='unifiedui')
    op.create_index('ix_tags_tenant', 'tags', ['tenant_id'], unique=False, schema='unifiedui')
    op.create_table('autonomous_agent_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('autonomous_agent_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['autonomous_agent_id'], ['unifiedui.autonomous_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'principal_id'], ['unifiedui.principals.tenant_id', 'unifiedui.principals.principal_id'], name='fk_autonomous_agent_members_principal', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('autonomous_agent_id', 'principal_id', name='uq_autonomous_agent_members'),
    schema='unifiedui'
    )
    op.create_index('ix_aam_autonomous_agent', 'autonomous_agent_members', ['autonomous_agent_id'], unique=False, schema='unifiedui')
    op.create_index('ix_aam_principal', 'autonomous_agent_members', ['principal_id'], unique=False, schema='unifiedui')
    op.create_table('autonomous_agent_tags',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('autonomous_agent_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['autonomous_agent_id'], ['unifiedui.autonomous_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['unifiedui.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'tag_id', 'autonomous_agent_id'),
    schema='unifiedui'
    )
    op.create_index('ix_aat_autonomous_agent', 'autonomous_agent_tags', ['autonomous_agent_id'], unique=False, schema='unifiedui')
    op.create_index('ix_aat_tag', 'autonomous_agent_tags', ['tag_id'], unique=False, schema='unifiedui')
    op.create_table('autonomous_agent_user_favorites',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('autonomous_agent_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['autonomous_agent_id'], ['unifiedui.autonomous_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['unifiedui.principals.tenant_id', 'unifiedui.principals.principal_id'], name='fk_autonomous_agent_user_favorites_principal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id', 'autonomous_agent_id'),
    schema='unifiedui'
    )
    op.create_index('ix_aauf_autonomous_agent', 'autonomous_agent_user_favorites', ['autonomous_agent_id'], unique=False, schema='unifiedui')
    op.create_index('ix_aauf_user', 'autonomous_agent_user_favorites', ['user_id'], unique=False, schema='unifiedui')
    op.create_table('chat_agent_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('chat_agent_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['chat_agent_id'], ['unifiedui.chat_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'principal_id'], ['unifiedui.principals.tenant_id', 'unifiedui.principals.principal_id'], name='fk_chat_agent_members_principal', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_agent_id', 'principal_id', name='uq_chat_agent_members'),
    schema='unifiedui'
    )
    op.create_index('ix_cam_chat_agent', 'chat_agent_members', ['chat_agent_id'], unique=False, schema='unifiedui')
    op.create_index('ix_cam_principal', 'chat_agent_members', ['principal_id'], unique=False, schema='unifiedui')
    op.create_table('chat_agent_tags',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('chat_agent_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['chat_agent_id'], ['unifiedui.chat_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['unifiedui.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'tag_id', 'chat_agent_id'),
    schema='unifiedui'
    )
    op.create_index('ix_cat_chat_agent', 'chat_agent_tags', ['chat_agent_id'], unique=False, schema='unifiedui')
    op.create_index('ix_cat_tag', 'chat_agent_tags', ['tag_id'], unique=False, schema='unifiedui')
    op.create_table('chat_agent_user_favorites',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('chat_agent_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['chat_agent_id'], ['unifiedui.chat_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['unifiedui.principals.tenant_id', 'unifiedui.principals.principal_id'], name='fk_chat_agent_user_favorites_principal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id', 'chat_agent_id'),
    schema='unifiedui'
    )
    op.create_index('ix_cauf_chat_agent', 'chat_agent_user_favorites', ['chat_agent_id'], unique=False, schema='unifiedui')
    op.create_index('ix_cauf_user', 'chat_agent_user_favorites', ['user_id'], unique=False, schema='unifiedui')
    op.create_table('chat_widget_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('chat_widget_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['chat_widget_id'], ['unifiedui.chat_widgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'principal_id'], ['unifiedui.principals.tenant_id', 'unifiedui.principals.principal_id'], name='fk_chat_widget_members_principal', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_widget_id', 'principal_id', name='uq_chat_widget_members'),
    schema='unifiedui'
    )
    op.create_index('ix_cwm_chat_widget', 'chat_widget_members', ['chat_widget_id'], unique=False, schema='unifiedui')
    op.create_index('ix_cwm_principal', 'chat_widget_members', ['principal_id'], unique=False, schema='unifiedui')
    op.create_table('chat_widget_tags',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('chat_widget_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['chat_widget_id'], ['unifiedui.chat_widgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['unifiedui.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'tag_id', 'chat_widget_id'),
    schema='unifiedui'
    )
    op.create_index('ix_cwt_chat_widget', 'chat_widget_tags', ['chat_widget_id'], unique=False, schema='unifiedui')
    op.create_index('ix_cwt_tag', 'chat_widget_tags', ['tag_id'], unique=False, schema='unifiedui')
    op.create_table('chat_widget_user_favorites',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('chat_widget_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['chat_widget_id'], ['unifiedui.chat_widgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['unifiedui.principals.tenant_id', 'unifiedui.principals.principal_id'], name='fk_chat_widget_user_favorites_principal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id', 'chat_widget_id'),
    schema='unifiedui'
    )
    op.create_index('ix_cwuf_chat_widget', 'chat_widget_user_favorites', ['chat_widget_id'], unique=False, schema='unifiedui')
    op.create_index('ix_cwuf_user', 'chat_widget_user_favorites', ['user_id'], unique=False, schema='unifiedui')
    op.create_table('conversations',
    sa.Column('chat_agent_id', sa.String(length=36), nullable=False),
    sa.Column('ext_conversation_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['chat_agent_id'], ['unifiedui.chat_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='unifiedui'
    )
    op.create_index('ix_conversations_chat_agent', 'conversations', ['chat_agent_id'], unique=False, schema='unifiedui')
    op.create_index('ix_conversations_tenant', 'conversations', ['tenant_id'], unique=False, schema='unifiedui')
    op.create_table('credential_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['unifiedui.credentials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'principal_id'], ['unifiedui.principals.tenant_id', 'unifiedui.principals.principal_id'], name='fk_credential_members_principal', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id', 'principal_id', name='uq_credential_members'),
    schema='unifiedui'
    )
    op.create_index('ix_crm_credential', 'credential_members', ['credential_id'], unique=False, schema='unifiedui')
    op.create_index('ix_crm_principal', 'credential_members', ['principal_id'], unique=False, schema='unifiedui')
    op.create_table('credential_tags',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['unifiedui.credentials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['unifiedui.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'tag_id', 'credential_id'),
    schema='unifiedui'
    )
    op.create_index('ix_crt_credential', 'credential_tags', ['credential_id'], unique=False, schema='unifiedui')
    op.create_index('ix_crt_tag', 'credential_tags', ['tag_id'], unique=False, schema='unifiedui')
    op.create_table('custom_group_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('custom_group_id', sa.String(length=50), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'custom_group_id'], ['unifiedui.principals.tenant_id', 'unifiedui.principals.principal_id'], name='fk_custom_group_members_custom_group', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'principal_id'], ['unifiedui.principals.tenant_id', 'unifiedui.principals.principal_id'], name='fk_custom_group_members_principal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'custom_group_id', 'principal_id', name='uq_custom_group_members'),
    schema='unifiedui'
    )
    op.create_index('ix_cgm_custom_group', 'custom_group_members', ['custom_group_id'], unique=False, schema='unifiedui')
    op.create_index('ix_cgm_principal', 'custom_group_members', ['principal_id'], unique=False, schema='unifiedui')
    op.create_index('ix_cgm_tenant', 'custom_group_members', ['tenant_id'], unique=False, schema='unifiedui')
    op.create_table('re_act_agent_versions',
    sa.Column('chat_agent_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('ai_model_ids', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('system_prompt', sa.String(length=8000), nullable=True),
    sa.Column('tool_ids', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('security_prompt', sa.String(length=8000), nullable=True),
    sa.Column('tool_use_prompt', sa.String(length=8000), nullable=True),
    sa.Column('response_prompt', sa.String(length=8000), nullable=True),
    sa.Column('greeting_messages', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['chat_agent_id'], ['unifiedui.chat_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_agent_id', 'version', name='uq_re_act_agent_version'),
    schema='unifiedui'
    )
    op.create_index('ix_re_act_agent_versions_agent', 're_act_agent_versions', ['chat_agent_id'], unique=False, schema='unifiedui')
    op.create_index('ix_re_act_agent_versions_agent_version', 're_act_agent_versions', ['chat_agent_id', 'version'], unique=False, schema='unifiedui')
    op.create_table('tenant_ai_models',
    sa.Column('type', sa.Enum('LLM_MODEL', 'EMBEDDING_MODEL', name='ai_model_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('provider', sa.Enum('AZURE_OPENAI', 'OPENAI', 'ANTHROPIC', 'GOOGLE_GENAI', 'OLLAMA', 'MISTRAL', 'GROQ', name='ai_model_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('purpose_groups', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['unifiedui.credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_ai_model_tenant_name'),
    schema='unifiedui'
    )
    op.create_index('ix_tenant_ai_models_tenant', 'tenant_ai_models', ['tenant_id'], unique=False, schema='unifiedui')
    op.create_table('tenant_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('READER', 'TENANT_GLOBAL_ADMIN', 'CUSTOM_GROUPS_ADMIN', 'CUSTOM_GROUP_CREATOR', 'CHAT_AGENTS_ADMIN', 'CHAT_AGENTS_CREATOR', 'CREDENTIALS_ADMIN', 'CREDENTIALS_CREATOR', 'CONVERSATIONS_ADMIN', 'CONVERSATIONS_CREATOR', 'AUTONOMOUS_AGENTS_ADMIN', 'AUTONOMOUS_AGENTS_CREATOR', 'CHAT_WIDGETS_ADMIN', 'CHAT_WIDGETS_CREATOR', 'REACT_AGENT_ADMIN', 'REACT_AGENT_CREATOR', 'TENANT_AI_MODELS_ADMIN', 'EXTERNAL_APPS_ADMIN', 'EXTERNAL_APPS_CREATOR', name='tenant_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'principal_id'], ['unifiedui.principals.tenant_id', 'unifiedui.principals.principal_id'], name='fk_tenant_members_principal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'principal_id', 'role', name='uq_tenant_members'),
    schema='unifiedui'
    )
    op.create_index('ix_tm_principal', 'tenant_members', ['principal_id'], unique=False, schema='unifiedui')
    op.create_index('ix_tm_tenant', 'tenant_members', ['tenant_id'], unique=False, schema='unifiedui')
    op.create_table('tools',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['unifiedui.credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tool_tenant_name'),
    schema='unifiedui'
    )
    op.create_index('ix_tools_tenant', 'tools', ['tenant_id'], unique=False, schema='unifiedui')
    op.create_table('conversation_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['unifiedui.conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'principal_id'], ['unifiedui.principals.tenant_id', 'unifiedui.principals.principal_id'], name='fk_conversation_members_principal', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'principal_id', name='uq_conversation_members'),
    schema='unifiedui'
    )
    op.create_index('ix_cm_conversation', 'conversation_members', ['conversation_id'], unique=False, schema='unifiedui')
    op.create_index('ix_cm_principal', 'conversation_members', ['principal_id'], unique=False, schema='unifiedui')
    op.create_table('conversation_user_favorites',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['unifiedui.conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['unifiedui.principals.tenant_id', 'unifiedui.principals.principal_id'], name='fk_conversation_user_favorites_principal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['unifiedui.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id', 'conversation_id'),
    schema='unifiedui'
    )
    op.create_index('ix_cuf_conversation', 'conversation_user_favorites', ['conversation_id'], unique=False, schema='unifiedui')
    op.create_index('ix_cuf_user', 'conversation_user_favorites', ['user_id'], unique=False, schema='unifiedui')
    op.create_table('tool_members',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tool_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'principal_id'], ['unifiedui.principals.tenant_id', 'unifiedui.principals.principal_id'], name='fk_tool_members_principal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['unifiedui.tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id', 'principal_id', name='uq_tool_members'),
    schema='unifiedui'
    )
    op.create_index('ix_tool_members_principal', 'tool_members', ['principal_id'], unique=False, schema='unifiedui')
    op.create_index('ix_tool_members_tool', 'tool_members', ['tool_id'], unique=False, schema='unifiedui')
    op.create_table('tool_tags',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('updated_at', HighPrecisionDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['unifiedui.tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['unifiedui.tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'tag_id', 'tool_id'),
    schema='unifiedui'
    )
    op.create_index('ix_tt_tag', 'tool_tags', ['tag_id'], unique=False, schema='unifiedui')
    op.create_index('ix_tt_tool', 'tool_tags', ['tool_id'], unique=False, schema='unifiedui')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tt_tool', table_name='tool_tags', schema='unifiedui')
    op.drop_index('ix_tt_tag', table_name='tool_tags', schema='unifiedui')
    op.drop_table('tool_tags', schema='unifiedui')
    op.drop_index('ix_tool_members_tool', table_name='tool_members', schema='unifiedui')
    op.drop_index('ix_tool_members_principal', table_name='tool_members', schema='unifiedui')
    op.drop_table('tool_members', schema='unifiedui')
    op.drop_index('ix_cuf_user', table_name='conversation_user_favorites', schema='unifiedui')
    op.drop_index('ix_cuf_conversation', table_name='conversation_user_favorites', schema='unifiedui')
    op.drop_table('conversation_user_favorites', schema='unifiedui')
    op.drop_index('ix_cm_principal', table_name='conversation_members', schema='unifiedui')
    op.drop_index('ix_cm_conversation', table_name='conversation_members', schema='unifiedui')
    op.drop_table('conversation_members', schema='unifiedui')
    op.drop_index('ix_tools_tenant', table_name='tools', schema='unifiedui')
    op.drop_table('tools', schema='unifiedui')
    op.drop_index('ix_tm_tenant', table_name='tenant_members', schema='unifiedui')
    op.drop_index('ix_tm_principal', table_name='tenant_members', schema='unifiedui')
    op.drop_table('tenant_members', schema='unifiedui')
    op.drop_index('ix_tenant_ai_models_tenant', table_name='tenant_ai_models', schema='unifiedui')
    op.drop_table('tenant_ai_models', schema='unifiedui')
    op.drop_index('ix_re_act_agent_versions_agent_version', table_name='re_act_agent_versions', schema='unifiedui')
    op.drop_index('ix_re_act_agent_versions_agent', table_name='re_act_agent_versions', schema='unifiedui')
    op.drop_table('re_act_agent_versions', schema='unifiedui')
    op.drop_index('ix_cgm_tenant', table_name='custom_group_members', schema='unifiedui')
    op.drop_index('ix_cgm_principal', table_name='custom_group_members', schema='unifiedui')
    op.drop_index('ix_cgm_custom_group', table_name='custom_group_members', schema='unifiedui')
    op.drop_table('custom_group_members', schema='unifiedui')
    op.drop_index('ix_crt_tag', table_name='credential_tags', schema='unifiedui')
    op.drop_index('ix_crt_credential', table_name='credential_tags', schema='unifiedui')
    op.drop_table('credential_tags', schema='unifiedui')
    op.drop_index('ix_crm_principal', table_name='credential_members', schema='unifiedui')
    op.drop_index('ix_crm_credential', table_name='credential_members', schema='unifiedui')
    op.drop_table('credential_members', schema='unifiedui')
    op.drop_index('ix_conversations_tenant', table_name='conversations', schema='unifiedui')
    op.drop_index('ix_conversations_chat_agent', table_name='conversations', schema='unifiedui')
    op.drop_table('conversations', schema='unifiedui')
    op.drop_index('ix_cwuf_user', table_name='chat_widget_user_favorites', schema='unifiedui')
    op.drop_index('ix_cwuf_chat_widget', table_name='chat_widget_user_favorites', schema='unifiedui')
    op.drop_table('chat_widget_user_favorites', schema='unifiedui')
    op.drop_index('ix_cwt_tag', table_name='chat_widget_tags', schema='unifiedui')
    op.drop_index('ix_cwt_chat_widget', table_name='chat_widget_tags', schema='unifiedui')
    op.drop_table('chat_widget_tags', schema='unifiedui')
    op.drop_index('ix_cwm_principal', table_name='chat_widget_members', schema='unifiedui')
    op.drop_index('ix_cwm_chat_widget', table_name='chat_widget_members', schema='unifiedui')
    op.drop_table('chat_widget_members', schema='unifiedui')
    op.drop_index('ix_cauf_user', table_name='chat_agent_user_favorites', schema='unifiedui')
    op.drop_index('ix_cauf_chat_agent', table_name='chat_agent_user_favorites', schema='unifiedui')
    op.drop_table('chat_agent_user_favorites', schema='unifiedui')
    op.drop_index('ix_cat_tag', table_name='chat_agent_tags', schema='unifiedui')
    op.drop_index('ix_cat_chat_agent', table_name='chat_agent_tags', schema='unifiedui')
    op.drop_table('chat_agent_tags', schema='unifiedui')
    op.drop_index('ix_cam_principal', table_name='chat_agent_members', schema='unifiedui')
    op.drop_index('ix_cam_chat_agent', table_name='chat_agent_members', schema='unifiedui')
    op.drop_table('chat_agent_members', schema='unifiedui')
    op.drop_index('ix_aauf_user', table_name='autonomous_agent_user_favorites', schema='unifiedui')
    op.drop_index('ix_aauf_autonomous_agent', table_name='autonomous_agent_user_favorites', schema='unifiedui')
    op.drop_table('autonomous_agent_user_favorites', schema='unifiedui')
    op.drop_index('ix_aat_tag', table_name='autonomous_agent_tags', schema='unifiedui')
    op.drop_index('ix_aat_autonomous_agent', table_name='autonomous_agent_tags', schema='unifiedui')
    op.drop_table('autonomous_agent_tags', schema='unifiedui')
    op.drop_index('ix_aam_principal', table_name='autonomous_agent_members', schema='unifiedui')
    op.drop_index('ix_aam_autonomous_agent', table_name='autonomous_agent_members', schema='unifiedui')
    op.drop_table('autonomous_agent_members', schema='unifiedui')
    op.drop_index('ix_tags_tenant', table_name='tags', schema='unifiedui')
    op.drop_index('ix_tags_name', table_name='tags', schema='unifiedui')
    op.drop_table('tags', schema='unifiedui')
    op.drop_index('ix_recent_visits_user_time', table_name='recent_visits', schema='unifiedui')
    op.drop_table('recent_visits', schema='unifiedui')
    op.drop_index('ix_principals_tenant', table_name='principals', schema='unifiedui')
    op.drop_index('ix_principals_principal_type', table_name='principals', schema='unifiedui')
    op.drop_index('ix_principals_mail', table_name='principals', schema='unifiedui')
    op.drop_index('ix_principals_display_name', table_name='principals', schema='unifiedui')
    op.drop_table('principals', schema='unifiedui')
    op.drop_index('ix_external_apps_tenant', table_name='external_apps', schema='unifiedui')
    op.drop_table('external_apps', schema='unifiedui')
    op.drop_index('ix_credentials_tenant', table_name='credentials', schema='unifiedui')
    op.drop_table('credentials', schema='unifiedui')
    op.drop_index('ix_chat_widgets_tenant', table_name='chat_widgets', schema='unifiedui')
    op.drop_table('chat_widgets', schema='unifiedui')
    op.drop_index('ix_chat_agents_tenant', table_name='chat_agents', schema='unifiedui')
    op.drop_table('chat_agents', schema='unifiedui')
    op.drop_index('ix_autonomous_agents_tenant', table_name='autonomous_agents', schema='unifiedui')
    op.drop_table('autonomous_agents', schema='unifiedui')
    op.drop_index('ix_tenant_org', table_name='tenants', schema='unifiedui')
    op.drop_table('tenants', schema='unifiedui')
    op.drop_index('ix_org_member_principal', table_name='organization_members', schema='unifiedui')
    op.drop_index('ix_org_member_org', table_name='organization_members', schema='unifiedui')
    op.drop_table('organization_members', schema='unifiedui')
    op.drop_index('ix_org_slug', table_name='organizations', schema='unifiedui')
    op.drop_index('ix_org_idp', table_name='organizations', schema='unifiedui')
    op.drop_table('organizations', schema='unifiedui')
    # ### end Alembic commands ###
