"""add_supported_widgets_to_chat_agents

Revision ID: a98a1760f645
Revises: 2577caa35eeb
Create Date: 2026-03-15 10:03:07.490790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a98a1760f645'
down_revision: Union[str, Sequence[str], None] = '2577caa35eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_agents', sa.Column('supported_widgets', sa.JSON().with_variant(mssql.JSON(), 'mssql').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'[]'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_agents', 'supported_widgets')
    # ### end Alembic commands ###
