"""add_principal_type_to_tenant_roles

Revision ID: aa47a1a1c134
Revises: 4f15ab679769
Create Date: 2025-12-17 10:56:08.793274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa47a1a1c134'
down_revision: Union[str, Sequence[str], None] = '4f15ab679769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add column as nullable
    op.add_column('tenant_roles', sa.Column('principal_type', sa.Enum('IDENTITY_USER', 'IDENTITY_GROUP', 'CUSTOM_GROUP', name='principal_type', native_enum=False, create_constraint=True), nullable=True))
    
    # Set default value for existing rows (assume IDENTITY_USER for existing data)
    op.execute("UPDATE tenant_roles SET principal_type = 'IDENTITY_USER' WHERE principal_type IS NULL")
    
    # Now make it NOT NULL
    op.alter_column('tenant_roles', 'principal_type', nullable=False)
    
    # Update constraints
    op.drop_constraint(op.f('uq_tenant_roles'), 'tenant_roles', type_='unique')
    op.create_unique_constraint('uq_tenant_roles', 'tenant_roles', ['tenant_id', 'principal_id', 'principal_type', 'role'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_roles', 'tenant_roles', type_='unique')
    op.create_unique_constraint(op.f('uq_tenant_roles'), 'tenant_roles', ['tenant_id', 'principal_id', 'role'], postgresql_nulls_not_distinct=False)
    op.drop_column('tenant_roles', 'principal_type')
    # ### end Alembic commands ###
