"""add_ext_conversation_id_to_conversations

Revision ID: c8601860d5a8
Revises: 01743198757f
Create Date: 2026-01-05 20:45:40.044710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8601860d5a8'
down_revision: Union[str, Sequence[str], None] = '01743198757f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('ext_conversation_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'ext_conversation_id')
    # ### end Alembic commands ###
