"""Refactor permissions to roles model

Revision ID: e154058dadca
Revises: 0ee03c5be1e8
Create Date: 2025-12-20 13:32:39.011939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e154058dadca'
down_revision: Union[str, Sequence[str], None] = '0ee03c5be1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_member_roles',
    sa.Column('tenant_member_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('READER', 'GLOBAL_ADMIN', 'CUSTOM_GROUPS_ADMIN', 'CUSTOM_GROUP_CREATOR', 'APPLICATIONS_ADMIN', 'APPLICATIONS_CREATOR', 'CREDENTIALS_ADMIN', 'CREDENTIALS_CREATOR', 'CONVERSATIONS_ADMIN', 'CONVERSATIONS_CREATOR', 'AUTONOMOUS_AGENTS_ADMIN', 'AUTONOMOUS_AGENTS_CREATOR', name='tenant_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tenant_member_id'], ['tenant_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_member_id', 'role', name='uq_tenant_member_roles')
    )
    op.create_index('ix_tmr_tenant_member', 'tenant_member_roles', ['tenant_member_id'], unique=False)
    op.drop_index(op.f('ix_cmp_member'), table_name='conversation_member_permissions')
    op.drop_table('conversation_member_permissions')
    op.drop_index(op.f('ix_cgmp_member'), table_name='custom_group_member_permissions')
    op.drop_table('custom_group_member_permissions')
    op.drop_index(op.f('ix_crmp_member'), table_name='credential_member_permissions')
    op.drop_table('credential_member_permissions')
    op.drop_index(op.f('ix_tmp_tenant_member'), table_name='tenant_member_permissions')
    op.drop_table('tenant_member_permissions')
    op.drop_index(op.f('ix_amp_member'), table_name='application_member_permissions')
    op.drop_table('application_member_permissions')
    op.drop_index(op.f('ix_aamp_member'), table_name='autonomous_agent_member_permissions')
    op.drop_table('autonomous_agent_member_permissions')
    op.add_column('application_members', sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False))
    op.add_column('autonomous_agent_members', sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False))
    op.add_column('conversation_members', sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False))
    op.add_column('credential_members', sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False))
    op.add_column('custom_group_members', sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_action', native_enum=False, create_constraint=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_group_members', 'role')
    op.drop_column('credential_members', 'role')
    op.drop_column('conversation_members', 'role')
    op.drop_column('autonomous_agent_members', 'role')
    op.drop_column('application_members', 'role')
    op.create_table('autonomous_agent_member_permissions',
    sa.Column('autonomous_agent_member_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('permission', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.CheckConstraint("permission::text = ANY (ARRAY['READ'::character varying, 'WRITE'::character varying, 'ADMIN'::character varying]::text[])", name=op.f('permission_action')),
    sa.ForeignKeyConstraint(['autonomous_agent_member_id'], ['autonomous_agent_members.id'], name=op.f('autonomous_agent_member_permiss_autonomous_agent_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('autonomous_agent_member_permissions_pkey')),
    sa.UniqueConstraint('autonomous_agent_member_id', 'permission', name=op.f('uq_autonomous_agent_member_permissions'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_aamp_member'), 'autonomous_agent_member_permissions', ['autonomous_agent_member_id'], unique=False)
    op.create_table('application_member_permissions',
    sa.Column('application_member_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('permission', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.CheckConstraint("permission::text = ANY (ARRAY['READ'::character varying, 'WRITE'::character varying, 'ADMIN'::character varying]::text[])", name=op.f('permission_action')),
    sa.ForeignKeyConstraint(['application_member_id'], ['application_members.id'], name=op.f('application_member_permissions_application_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('application_member_permissions_pkey')),
    sa.UniqueConstraint('application_member_id', 'permission', name=op.f('uq_application_member_permissions'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_amp_member'), 'application_member_permissions', ['application_member_id'], unique=False)
    op.create_table('tenant_member_permissions',
    sa.Column('tenant_member_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('permission', sa.VARCHAR(length=23), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.CheckConstraint("permission::text = ANY (ARRAY['READER'::character varying::text, 'GLOBAL_ADMIN'::character varying::text, 'CUSTOM_GROUPS_ADMIN'::character varying::text, 'APPLICATIONS_ADMIN'::character varying::text, 'CREDENTIALS_ADMIN'::character varying::text, 'AUTONOMOUS_AGENTS_ADMIN'::character varying::text])", name=op.f('tenant_role')),
    sa.ForeignKeyConstraint(['tenant_member_id'], ['tenant_members.id'], name=op.f('tenant_member_permissions_tenant_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tenant_member_permissions_pkey')),
    sa.UniqueConstraint('tenant_member_id', 'permission', name=op.f('uq_tenant_member_permissions'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tmp_tenant_member'), 'tenant_member_permissions', ['tenant_member_id'], unique=False)
    op.create_table('credential_member_permissions',
    sa.Column('credential_member_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('permission', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.CheckConstraint("permission::text = ANY (ARRAY['READ'::character varying, 'WRITE'::character varying, 'ADMIN'::character varying]::text[])", name=op.f('permission_action')),
    sa.ForeignKeyConstraint(['credential_member_id'], ['credential_members.id'], name=op.f('credential_member_permissions_credential_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('credential_member_permissions_pkey')),
    sa.UniqueConstraint('credential_member_id', 'permission', name=op.f('uq_credential_member_permissions'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_crmp_member'), 'credential_member_permissions', ['credential_member_id'], unique=False)
    op.create_table('custom_group_member_permissions',
    sa.Column('custom_group_member_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('permission', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.CheckConstraint("permission::text = ANY (ARRAY['READ'::character varying, 'WRITE'::character varying, 'ADMIN'::character varying]::text[])", name=op.f('permission_action')),
    sa.ForeignKeyConstraint(['custom_group_member_id'], ['custom_group_members.id'], name=op.f('custom_group_member_permissions_custom_group_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('custom_group_member_permissions_pkey')),
    sa.UniqueConstraint('custom_group_member_id', 'permission', name=op.f('uq_custom_group_member_permissions'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_cgmp_member'), 'custom_group_member_permissions', ['custom_group_member_id'], unique=False)
    op.create_table('conversation_member_permissions',
    sa.Column('conversation_member_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('permission', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.CheckConstraint("permission::text = ANY (ARRAY['READ'::character varying, 'WRITE'::character varying, 'ADMIN'::character varying]::text[])", name=op.f('permission_action')),
    sa.ForeignKeyConstraint(['conversation_member_id'], ['conversation_members.id'], name=op.f('conversation_member_permissions_conversation_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_member_permissions_pkey')),
    sa.UniqueConstraint('conversation_member_id', 'permission', name=op.f('uq_conversation_member_permissions'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_cmp_member'), 'conversation_member_permissions', ['conversation_member_id'], unique=False)
    op.drop_index('ix_tmr_tenant_member', table_name='tenant_member_roles')
    op.drop_table('tenant_member_roles')
    # ### end Alembic commands ###
