"""Add audit fields to tag junction tables

Revision ID: fb92d04935a0
Revises: 172b16f13007
Create Date: 2025-12-26 08:08:58.187054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb92d04935a0'
down_revision: Union[str, Sequence[str], None] = '172b16f13007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_tags', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('application_tags', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('application_tags', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('application_tags', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('autonomous_agent_tags', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('autonomous_agent_tags', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('autonomous_agent_tags', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('autonomous_agent_tags', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('chat_widget_tags', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('chat_widget_tags', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('chat_widget_tags', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('chat_widget_tags', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('credential_tags', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('credential_tags', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('credential_tags', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('credential_tags', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('development_platform_tags', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('development_platform_tags', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('development_platform_tags', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('development_platform_tags', sa.Column('updated_by', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('development_platform_tags', 'updated_by')
    op.drop_column('development_platform_tags', 'created_by')
    op.drop_column('development_platform_tags', 'updated_at')
    op.drop_column('development_platform_tags', 'created_at')
    op.drop_column('credential_tags', 'updated_by')
    op.drop_column('credential_tags', 'created_by')
    op.drop_column('credential_tags', 'updated_at')
    op.drop_column('credential_tags', 'created_at')
    op.drop_column('chat_widget_tags', 'updated_by')
    op.drop_column('chat_widget_tags', 'created_by')
    op.drop_column('chat_widget_tags', 'updated_at')
    op.drop_column('chat_widget_tags', 'created_at')
    op.drop_column('autonomous_agent_tags', 'updated_by')
    op.drop_column('autonomous_agent_tags', 'created_by')
    op.drop_column('autonomous_agent_tags', 'updated_at')
    op.drop_column('autonomous_agent_tags', 'created_at')
    op.drop_column('application_tags', 'updated_by')
    op.drop_column('application_tags', 'created_by')
    op.drop_column('application_tags', 'updated_at')
    op.drop_column('application_tags', 'created_at')
    # ### end Alembic commands ###
