name: aihub-infra
services:
  aihub-postgres:
    image: postgres:16-alpine
    container_name: aihub-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=aihub
      - POSTGRES_PASSWORD=aihub_password
      - POSTGRES_DB=aihub
    volumes:
      - postgres_data_aihub:/var/lib/postgresql/data
    networks:
      - aihub_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aihub"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:8.2
    container_name: aihub-document-database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
    networks:
      - aihub_network

  redis:
    image: redis:8.4
    container_name: aihub-cache
    environment:
      REDIS_PASSWORD: admin
    command: ["redis-server", "--requirepass", "admin"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aihub_network

  rabbitmq:
    image: rabbitmq:4.2-management
    container_name: aihub-message-broker
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - aihub_network

  minio:
    image: minio/minio
    container_name: aihub-object-storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: adminminio
      MINIO_ROOT_PASSWORD: adminminio
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - aihub_network

  vault:
    image: hashicorp/vault:1.18
    container_name: aihub-secrets-vault
    ports:
      - "8200:8200"
    environment:
      # Dev-mode Token (nur lokal!)
      VAULT_DEV_ROOT_TOKEN_ID: admin
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -dev
    networks:
      - aihub_network
  
volumes:
  mongo_data:
  redis_data:
  rabbitmq_data:
  minio_data:
  postgres_data_aihub:

networks:
  aihub_network:
    name: aihub_network
    driver: bridge
